openapi: 3.0.0
info:
  title: Mangos Maintenance API
  description: API allowing to interact with the technical part of the databases
  license:
    name: Apache 2.0
  version: "1.0"
externalDocs:
  description: Instructions on how to deploy this WebApp
  url: https://github.com/Warkdev/maintenance-service/blob/master/README.md
servers:
- url: http://localhost:8081/maintenance-service
tags:
- name: version
  description: Operations about database version
- name: operation
  description: Maintenance operations on the database
paths:
  /operation/v1/cleanup:
    get:
      tags:
      - operation
      summary: Retrieves a list of all items which will be cleaned up if the clean-up
        operation is performed.
      description: This API is showing all items which will be cleaned up from the
        database.
      operationId: showCleanUpDB
      responses:
        "200":
          description: The list of items which will be cleaned-up is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Map'
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
    delete:
      tags:
      - operation
      summary: Clean-up all dead links from the database
      description: "This API is cleaning-up bans, links, uptimes info and logs from\
        \ the database for accounts/realms which were removed."
      operationId: cleanUpDB
      responses:
        "200":
          description: The database has been cleaned-up with a summary of the cleaning
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Map'
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
  /version/v1:
    get:
      tags:
      - version
      summary: Retrieves the database version
      description: This API is retrieving the database version from the database.
      operationId: getDbVersion
      responses:
        "200":
          description: The database version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DbVersionDTO'
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
components:
  schemas:
    DbVersionDTO:
      type: object
      properties:
        version:
          type: integer
          description: The version of the release
        structure:
          type: integer
          description: The current core structure level
        content:
          type: integer
          description: The current core content level
        description:
          type: string
          description: A short description of the latest database revision
        comment:
          type: string
          description: A comment about the latest database revision
    Map:
      type: object
      additionalProperties:
        type: object
      additionalPropertiesSchema:
        type: object